### ISSUE TITLE
Collaboration on a project

### ISSUE THREAD

**Issue by sanatg** [Adatta1276/Among-Us-JS-Edition#4]
HI @Adatta1276,
Sanat Gupta this side this is a very cool project do you want to collaborate on a open source project if you are interested i can share further details.

**Comment by Adatta1276** [comment]
> HI @Adatta1276,
> Sanat Gupta this side this is a very cool project do you want to collaborate on a project if you are interested i can share further details.
> 

Hi, thanks for chatting! Sorry, but I'm pretty busy now, I won't be able to collab on a project, maybe later sometime?

**Comment by sanatg** [comment]
Sure no problem :)

**Comment by sanatg** [comment]
Should I forward it on the mail

**Comment by Adatta1276** [comment]
> Should I forward it on the mail

Ok👍

**Comment by Adatta1276** [comment]
> Should I forward it on the mail

Btw do you know p5.js?

**Comment by sanatg** [comment]
yeah i do

**Comment by sanatg** [comment]
i have sent you the mail kindly check your inbox.

**Comment by Adatta1276** [comment]
Do you mean the mail with the details?

**Comment by sanatg** [comment]
meaning what is the project about and how do we go about it

**Comment by Adatta1276** [comment]
Thank you for your mails but I haven't recieved the details yet somehow 🤔

**Comment by sanatg** [comment]
So the project goes like this:

It is a notes app or web app that can be used to store notes,links etc encrypted in firebase basically an open source alternative to google keep.

Frameworks that can be used: i would prefer vanilla js but react is also ok.

this was the mail i sent.

**Comment by sanatg** [comment]
so are you interested??

**Comment by sanatg** [comment]
plz tell

**Comment by Adatta1276** [comment]
Hey Sanat, appreciate your mails, but I don't know anything when it comes
to ReactJS, however, vanilla js would be ok I think. So you're not using
any other libraries I guess (since u mentioned vanilla js) ?

**Comment by sanatg** [comment]
yes it would be ok we would be using some libraries like jquery etc but i can handle that

**Comment by sanatg** [comment]
so @Adatta1276  do you want to discuss further on call, online meet??

**Comment by Adatta1276** [comment]
> so @Adatta1276  do you want to discuss further on call, online meet??

No, I'm not available for calls or meets, sorry ☹️

**Comment by sanatg** [comment]
ok so then are you only available on mail

**Comment by Adatta1276** [comment]
Hmm, Sanat, really sorry to disappoint you, but I wouldn't be able to
collab with you on this project. However, shall we keep in touch through
GitHub? I'm currently working on a website of my own, you can check it out
here : https://github.com/adatta1276/adatta1276.github.io/

**Comment by Adatta1276** [comment]
No, I can't do that☹️

**Comment by sanatg** [comment]
Ok sure no problem then i am closing this issue.
